#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

RED='\033[0;31m'
NC='\033[0m' # No Color

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "main" ]; then
  echo "${RED}You can't push directly to main branch${NC}"
  exit 1
fi

yarn build
yarn test:component:ci && yarn test:e2e:ci
yarn lhci
# check coverage coverage/coverage-summary.json
linePercent=$(node -pe "JSON.parse(require('fs').readFileSync('coverage/coverage-summary.json', 'utf8')).total.lines.pct")
if [ $(echo "$linePercent < 80" | bc) -eq 1 ]; then
  echo "${RED}You can't push without 80% coverage${NC}"
  exit 1
fi
