#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "${RED}You can't commit directly to main branch${NC}"
  exit 1
fi
if [ "$branch" = "dev" ]; then
  echo "${RED}You can't commit directly to dev branch. Please create a feature, bug or hotfix branch then make a PR${NC}"
  exit 1
fi

valid_branch_regex='^((fix|feat|release)\/(\.|[a-zA-Z0-9\-])+)$'
message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."
echo "$branch"
echo "$valid_branch_regex"
if [[ ! $branch =~ $valid_branch_regex ]]; then
    echo "$message"
    exit 1
fi

# # Check if this is a versioning commit
# if git log -1 --pretty=%B | grep -q "release"; then
#   if [[ ! $branch =~ ^release\/ ]]; then
#     echo "${RED}You can't create a new version outside a release branch${NC}"
#     exit 1
#   fi
# fi

echo "${GREEN}Running lint${NC}"
npm run lint
echo "${GREEN}Running unit tests${NC}"
npm run test:unit:ci
echo "${GREEN}Running e2e tests${NC}"
npm run build
echo "${GREEN}Running lighthouse preformance and a11y test${NC}"
npm run lhci
