name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run Lint
      run: npm run lint

    - name: Run Unit Tests
      run: npm run test:unit:ci

    - name: Build Project
      run: npm run build

    - name: Run Lighthouse CI
      run: npm run lhci

    - name: Run Component Tests
      run: npm run test:component:ci

    - name: Run End-to-End Tests
      run: npm run test:e2e:ci
