name: Generate JSDoc and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jsdoc-vuejs
      run: npm install jsdoc-vuejs clean-jsdoc-theme

    - name: Build JSDoc
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./src
        output_dir: ./docs
        config_file: jsdoc.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
