name: Pull request ci

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-keys.outputs.key }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node 20
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --no-frozen-lockfile

      - name: Upload workspace
        uses: actions/upload-artifact@v2
        with:
          name: node-modules
          path: |
            node_modules
            **/package-lock.json

  Lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v2
        with:
          name: node-modules

      - name: Lint
        run: npm run lint

  Unit_Test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v2
        with:
          name: node-modules

      - name: Run unit test
        run: npm run test:unit:ci

  Component_Test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v2
        with:
          name: node-modules

      - name: Run component test
        run: npm run test:unit:ci

  E2E_Test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v2
        with:
          name: node-modules

      - name: Run E2E test
        run: npm run test:unit:ci

  Build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v2
        with:
          name: node-modules

      - name: Run build
        run: npm run build

  Lighthouse:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v2
        with:
          name: node-modules

      - name: Run lighthouse
        run: npm run lhci
