name: Pull request ci

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --no-frozen-lockfile

      - name: Lint validation
        run: npm lint

      - name: Run Unit Tests
        run: npm run test:unit:ci

      - name: Build
        run: npm build
